accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
 path('login/', views.login_operation, name='login'),
 path('logout/', views.logout_operation, name='logout'),
 path('profile/', views.profile_view, name='profile'),
 path('profile/myevent/', views.my_events, name='my_event'),
 path('profile/addnew/', views.add_new_event, name='add_new'),
 path('profile/register/', views.register_user, name='register_user'),
 path('profile/change_password/', views.change_password, name='change_password'),
 path('profile/event_submitted/<int:event_id>', views.event_submitted, name='event_submitted'),
 path('profile/edit_event/<int:event_id>', views.edit_own_event, name='edit_own_event'),
 path('profile/admin_panel/', views.admin_panel, name='admin_panel'),
 path('profile/verify_event/<int:event_id>', views.verify_event, name='verify_event')
]

eventing/urls.py
from django.urls import path
from eventing import views

app_name = 'eventing'

urlpatterns = [
 path('home/', views.home_loader, name='home_loader'),
 path('event/list/', views.event_list, name='event_list'),
 path('event/details/<int:event_id>', views.event_details, name='event_details'),
]

social_event/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from eventing import views

urlpatterns = [
    path('', views.home_loader, name='home_loader'),
    path('admin/', admin.site.urls),
    path('eventing/', include('eventing.urls')),
    path('accounts/', include('accounts.urls'))
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Profile(models.Model):
    """
    Represent a user's profile
    """
    class Meta:
        verbose_name = 'نمایه کاربری'
        verbose_name_plural = 'نمایه کاربری'

    user = models.OneToOneField\
        (User, on_delete=models.CASCADE, verbose_name='حساب کاربری')
    # important fields that are stored in User model:
    #   first_name, last_name, email, date_joined

    mobile = models.CharField('تلفن همراه', max_length=11, null=True, blank=False)

    PERSON = 1
    COMPANY = 2
    user_type_choices = ((PERSON, 'حقیقی'), (COMPANY, 'حقوقی'))
    user_type = models.IntegerField\
        ('نوع کاربری', choices=user_type_choices, null=True, blank=True)
    birth_date = models.DateField('تاریخ تولد', null=True, blank=True)
    address = models.TextField('آدرس', null=True, blank=True)
    organ_name = models.CharField('سازمان یا نام رسمی', max_length=50, null=False, blank=False)
    profile_image = models.ImageField('تصویر', upload_to='users/profile_images/', null=True, blank=True)

    def __str__(self):

        if self.user.first_name:
            show_name = self.user.get_full_name()
        else:
            show_name = self.organ_name
        return show_name


class Submit(models.Model):
    """
    Represent Submit model
    """
    class Meta:
        verbose_name = 'ثبت نام'
        verbose_name_plural = 'ثبت نام'

    submitted_user = models.ForeignKey\
        ('Profile', on_delete=models.PROTECT, blank=False, verbose_name='ثبت نام کننده')
    submitted_event = models.ForeignKey\
        ('eventing.Event', on_delete=models.PROTECT, blank=False, verbose_name='رویداد')
    cancel = models.BooleanField('وضعیت ثبت نام', null=False, default=False)
    submit_time = models.DateTimeField('زمان ثبت نام', blank=False, auto_now_add=True)

    def __str__(self):
        """
        override Submit models *string representation* method
        """
        submitter = self.submitted_user.user.get_full_name()
        event = self.submitted_event.title
        return 'ثبت نام کننده:{} -- رویداد:{}'.format(submitter, event)

    def cancel_submit(self):
        """
        user cancel submitted event
        """
        self.cancel = True

eventing/models.py
from django.db import models


class Event(models.Model):
    """
    Represents an event
    """
    class Meta:
        verbose_name = "رویداد"
        verbose_name_plural = "رویداد"

    title = models.CharField('عنوان', max_length=150, unique=True, blank=False)

    subject_choices = (
        ('computer science', 'علوم رایانه'),
        ('data science', 'علم داده'),
        ('big data', 'کلان داده'),
        ('artificial intelligence', 'هوش مصنوعی'),
        ('security', 'امنیت'),
        ('software engineering', 'مهندسی نرافزار'),
        ('develop', 'توسعه‌ی نرم افزار'),
        ('cryptography', 'رمزنگاری'),
        ('crypto currency', 'رمز ارز'),
        ('IOT', 'اینترنت اشیا'),
        ('startup', 'استارتاپ'),
    )
    subject = models.CharField('موضوع', choices=subject_choices, max_length=30, blank=False)
    tags = models.CharField('برچسب ها', max_length=70, null=True, blank=True)
    organizer = models.ForeignKey\
        ('accounts.Profile', on_delete=models.PROTECT, verbose_name='برگزار کننده')
    start_date = models.DateTimeField('زمان شروع', blank=False)
    end_date = models.DateTimeField('زمان پایان', blank=False)
    details = models.TextField('درمورد رویداد', max_length=2000, blank=False)
    poster = models.ImageField('پوستر', upload_to='event_posters/', blank=False)
    trailer = models.FileField('پیش نمایش', upload_to='event_trailers', null=True, blank=True)
    '#Represent situation of each event'
    EVENT_NOT_STARTED = 1
    EVENT_DONE = 2
    EVENT_STARTED = 3
    EVENT_CANCELED = 4
    NOT_VERIFY = 5
    situation_choices = (
        (EVENT_NOT_STARTED, 'رویداد آغاز نشده'),
        (EVENT_STARTED, 'رویداد آغاز شده'),
        (EVENT_DONE, 'رویداد پایان یافت'),
        (EVENT_CANCELED, 'رویداد لغو شده'),
        (NOT_VERIFY, 'در انتظار تایید')
    )
    situation = models.IntegerField\
        ('وضعیت رویداد', blank=True, choices=situation_choices, default=NOT_VERIFY)
    verify = models.BooleanField('تایید', null=False, blank=True, default=False)
    cancel = models.BooleanField('لغو', null=False, blank=True, default=False)
    end = models.BooleanField('پایان', null=False, blank=True, default=False)
    made_time = models.DateTimeField('زمان ایجاد', auto_now_add=True)

    def __str__(self):
        """
        override Event models *string representation* method
        """
        title = self.title
        if self.organizer.organ_name is not None:
            organizer = self.organizer.organ_name
        else:
            organizer = self.organizer.user.get_full_name()

        return 'عنوان:{}--زمان:{}--برگزار کننده:{}'.format(title, self.start_date, organizer)

    def cancel_event(self):
        """
        user/organizer canceled event
        """
        self.cancel = True
        self.situation = Event.EVENT_CANCELED

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from accounts.models import Profile, User
from eventing.models import Event


class RegisterForm(UserCreationForm):
    """
    client signup form
    """
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserEdit(UserChangeForm):
    """
    users can change 'first name', 'last name', 'email'
    """
    class Meta(UserChangeForm.Meta):
        fields = ['first_name', 'last_name', 'email']
    password = None


class ProfileEdit(forms.ModelForm):
    """
    users can change 'mobile', 'address, 'user type account', 'organ name', 'birth date' and 'profile image'
    """
    class Meta:
        model = Profile
        fields = ['mobile', 'address', 'user_type', 'organ_name', 'birth_date', 'profile_image']
        user_type_choices = Profile.user_type_choices


class CreatEvent(forms.ModelForm):
    """
    user create new own event
    """
    class Meta:
        model = Event
        fields = ['title', 'subject', 'details', 'tags', 'start_date', 'end_date', 'poster']


class EditEvent(forms.ModelForm):
    """
    user can edit own created event
    """
    class Meta:
        model = Event
        fields = ['title', 'subject', 'details', 'start_date', 'end_date', 'tags', 'poster', 'cancel']


class VerifyEvent(forms.ModelForm):
    """
    admin can verify and edit event
    """
    class Meta:
        model = Event
        fields = ['title', 'subject', 'details', 'start_date', 'end_date',
                  'tags', 'poster', 'cancel', 'verify']

accounts/views.py
from audioop import reverse
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import logout, authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from accounts.models import Profile, Submit
from eventing.models import Event
from accounts.forms import RegisterForm, UserEdit, ProfileEdit, CreatEvent, EditEvent, VerifyEvent


def register_user(request):
    """
    method for the client can register
    """
    context = {}
    reg_form = RegisterForm(request.POST)
    if request.method == 'POST':
        if reg_form.is_valid():
            new_user = reg_form.save()
            profile = Profile.objects.create(user=new_user, organ_name='بدون سازمان')
            login(request, new_user)
            return HttpResponseRedirect(reverse('accounts:profile'))
        else:
            context = {
                'reg_form': reg_form,
            }
    return render(request, 'accounts/register.html', context)


def login_operation(request):
    """
    login method
    """
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if request.GET.get('next'):
                return HttpResponseRedirect(request.GET.get('next'))
            return HttpResponseRedirect(reverse('eventing:home_loader'))
        else:
            context = {
                'username': username,
                'error': 'کاربر یافت نشد'
            }
    else:
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('eventing:home_loader'))

        context = {}

    return render(request, 'accounts/login_page.html', context)


def logout_operation(request):
    """
    logout method
    """
    logout(request)
    return HttpResponseRedirect(reverse('accounts:login'))


def only_admin(view_func):
    """
    this method allowed to admin to access special task and templates
    """
    def wrapper_function(request, *args, **kwargs):
        group = None
        if request.user.groups.exists():
            group = request.user.groups.all()[0].name

        if group == 'admin':
            return view_func(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('eventing:home_loader'))
    return wrapper_function


@login_required
@only_admin
def admin_panel(request):
    """
    render admin panel
    """
    verified = Event.objects.filter(Q(cancel=False) and Q(verify=True)).order_by('-made_time')
    not_verified = Event.objects.filter(Q(cancel=False) and Q(verify=False)).order_by('-made_time')
    context = {
        'verified': verified,
        'not_verified': not_verified,
    }
    return render(request, 'accounts/admin_panel.html', context)


@login_required
@only_admin
def verify_event(request, event_id):
    event = Event.objects.get(pk=event_id)
    organizer = event.organizer
    if request.method == 'POST':
        v_event = VerifyEvent(request.POST, files=request.FILES, instance=event)
        if v_event.is_valid():
            v_event.save()
            if v_event.cleaned_data['verify']:
                event.situation = Event.EVENT_NOT_STARTED
                event.save()
            if v_event.cleaned_data['cancel']:
                event.situation = Event.EVENT_CANCELED
                event.save()
            return HttpResponseRedirect((reverse('accounts:admin_panel')))
    else:
        v_event = VerifyEvent(instance=event)
        context = {
            'v_event': v_event,
            'event': event,
            'organizer': organizer,
        }
        return render(request, 'accounts/event_verify.html', context)


@login_required
def change_password(request):
    """
    user can change username and password
    """
    if request.method == 'POST':
        change_form = PasswordChangeForm(request.user, request.POST)
        if change_form.is_valid():
            user = change_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'گذر واژه با موفقیت تغییر کرد')
            return HttpResponseRedirect(reverse('accounts:change_password'))
        else:
            messages.error(request, 'لطفا خطا های زیر را بررسی کنید')
    else:
        change_form = PasswordChangeForm(request.user)
    context = {
        'change_form': change_form
    }
    return render(request, 'accounts/change_password.html', context)


@login_required
def profile_view(request):
    """
    user profile loader

    """
    if request.method == 'POST':
        user_field = UserEdit(request.POST, instance=request.user)
        profile_field = ProfileEdit(request.POST, files=request.FILES, instance=request.user.profile)
        if user_field.is_valid() and profile_field.is_valid():
            user_field.save()
            profile_field.save()
            return HttpResponseRedirect((reverse('accounts:profile')))
    else:
        user_field = UserEdit(instance=request.user)
        profile_field = ProfileEdit(instance=request.user.profile)

    profile = request.user.profile
    context = {
        'profile': profile,
        'user_field': user_field,
        'profile_filed': profile_field,
    }
    return render(request, 'accounts/profile_page.html', context)


@login_required
def my_events(request):
    """
    user can show own events
    """
    i_submitted = Submit.objects.filter\
        (Q(submitted_user=request.user.profile) & Q(cancel=False)).order_by('-submit_time')
    i_added = Event.objects.filter\
        (Q(organizer=request.user.profile)).order_by('-made_time')
    context = {
            'i_submitted': i_submitted,
            'i_added': i_added,
    }
    return render(request, 'accounts/profile_myevent.html', context)


@login_required
def event_submitted(request, event_id):
    """
    user can cancel submitted event
    """
    event = Event.objects.get(pk=event_id)
    user = request.user.profile
    context = {
        'event': event
    }
    '#Unsubmit event'
    if request.method == 'POST':
        try:
            assert not check_submitted(user, event), 'شما در این رویداد ثبت نام نکرده اید'
            submit = Submit.objects.get(submitted_user=user, submitted_event=event, cancel=False)
            submit.cancel = True
            submit.save()
            return HttpResponseRedirect(reverse('accounts:my_event'))
        except Exception as e:
            context['error'] = str(e)
        # ----
    return render(request, 'accounts/event_submitted.html', context)


def check_submitted(user, event):
    """
    check user are submitted specific event
    """
    if Submit.objects.filter(submitted_user=user, submitted_event=event, cancel=False).exists():
        return False
    else:
        return True


@login_required
def add_new_event(request):
    """
    user can add new event
    """
    context = {}
    if request.method == "POST":
        new_event = CreatEvent(request.POST, files=request.FILES)
        if new_event.is_valid():
            b = new_event.save(commit=False)
            b.organizer = request.user.profile
            b.save()
            return HttpResponseRedirect(reverse('accounts:my_event'))
    else:
        new_event = CreatEvent()
        context = {
            'new_event': new_event
        }
    return render(request, 'accounts/add_new_event.html', context)


@login_required
def edit_own_event(request, event_id):
    """
    user can edit or cancel own event
    """
    event = Event.objects.get(pk=event_id)
    user = request.user.profile
    subscribed = Submit.objects.filter(Q(submitted_event=event) and Q(cancel=False))

    if check_event_owner(user, event):
        if request.method == 'POST':
            edit_event = EditEvent(request.POST, files=request.FILES, instance=event)
            if edit_event.is_valid():
                edit_event.save()
                if edit_event.cleaned_data['cancel']:
                    event.situation = Event.EVENT_CANCELED
                    event.save()
                return HttpResponseRedirect((reverse('accounts:my_event')))
        else:
            edit_event = EditEvent(instance=event)
            context = {
                'edit_event': edit_event,
                'event': event,
                'subscribed': subscribed
            }
            return render(request, 'accounts/edit_event.html', context)
    else:
        raise Http404('شما اجازه دسترسی به این صفحه را ندارید')


def check_event_owner(user, event):
    if event.organizer == user:
        return True
    else:
        return False

accounts/templates/accounts/base_account.html
{% extends "eventing/base_page.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static "accounts/css/accounts.css" %}">
{% endblock %}

accounts/templates/accounts/change_password.html
{% extends "accounts/base_account.html" %}
{% load static %}
{% block title %}تغییر گذرواژه{% endblock %}
{% block slider %}{% endblock %}

{% block main_content %}
<div class="text-center my-login shadow-lg p-3 mb-5 bg-white rounded">
    <form class="form-signin" action="#" method="post">
        {% csrf_token %}
        {% if change_form.errors %}
            <div class="alert alert-danger">
            <ul>
                {{change_form.errors}}
            </ul>
            </div>
        {% endif %}
        <img class="mb-4" src="{% static 'accounts/images/Edit.png' %}" alt="" width="85" height="85">
        <h4 class="mb-3 font-weight-normal">ابتدا گذر واژه فعلی و سپس گذر واژه جدید را وارد کنید</h4>
        <label for="id_old_password" class="sr-only">گذرواژه فعلی</label>
            <input type="password" id="id_old_password" class="form-control" placeholder="گذر واژه فعلی" required name="old_password">
         <label for="id_new_password1" class="sr-only"> گذرواژه جدید</label>
            <input type="password" id="id_new_password1" class="form-control" placeholder="گذر واژه جدید" required name="new_password1">
        <label for="id_new_password2" class="sr-only">تایید گذرواژه</label>
            <input type="password" id="id_new_password2" class="form-control" placeholder="تایید گذر واژه" required name="new_password2">
        <div class="checkbox mb-3">
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">ثبت تغییرات</button>
        <p class="mt-5 mb-3 text-muted">&copy; 1399 </p>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/event_submitted.html
{% extends "eventing/base_page.html" %}
{% load static %}
{% block title %}{{ event.title }}{% endblock %}
{% block slider %}{% endblock %}

{% block main_content %}
<div class="container container-fluid">
    <div class="row mb-2 main-details">
        <div class="col-md-8">
            <div class="event-poster-details">
                <img src="{{ event.poster.url }}" style="width: 100%;height: 100%">
            </div>
            <div class="detail-content"></div>
        </div>
        <div class="col-md-4">
            <div style="padding: 10px 0 20px 0">
                <h5 style="color: #007bff"><strong>{{ event.title }}</strong></h5>
                <dl class="event_detail">
                    <dt>موضوع:</dt>
                    <dd>{{ event.get_subject_display }}</dd>
                    <dt>برگزار کننده:</dt>
                    <dd>{{ event.organizer }}</dd>
                    <dt>شروع:</dt>
                    <dd>{{ event.start_date|date:"l n/j ساعت H:i" }}</dd>
                    <dt>پایان:</dt>
                    <dd>{{ event.end_date|date:"l n/j ساعت H:i" }}</dd>
                    <dt>وضعیت رویداد:</dt>
                    <dd>{{ event.get_situation_display }}</dd>
                </dl>
                <div class="text-center">
                    <form action="#" method="post">
                        {% csrf_token %}
                        <button name="submit_action" type="submit" class="btn btn-danger">لغو ثبت نام</button>
                    </form>
                    {% if error %}
                        <span class="alert alert-danger" style="padding: 10px">
                            {{ error }}
                        </span>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/login_page.html
{% extends "accounts/base_account.html" %}
{% load static %}
{% block title %}ورود کاربران{% endblock %}
{% block slider %}{% endblock %}

{% block main_content %}
<div class="text-center my-login shadow-lg p-3 mb-5 bg-white rounded">
    <form class="form-signin" action="#" method="post">
        {% csrf_token %}
        {% if error %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endif %}
        <img class="mb-4" src="{% static 'accounts/images/login.png' %}" alt="" width="85" height="85">
        <h1 class="h3 mb-3 font-weight-normal">لطفا وارد شوید</h1>
        <label for="inputUsername" class="sr-only">نام کاربری</label>
            <input type="text" id="inputUsername" class="form-control"
                   placeholder="نام کاربری" required autofocus value="{{ username }}" name="username">
        <label for="inputPassword" class="sr-only">رمزعبور</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="رمزعبور" required name="password">
        <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> مرا به یاد داشته باش
        </label>
        </div>
            <div style="margin-bottom: 10px"><a href="{% url 'accounts:register_user' %}"
                    style="text-decoration: none; color: #bd2130">
                اگر حساب کاربری ندارید ابتدا عضو شوید</a></div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">ورود</button>
        <p class="mt-5 mb-3 text-muted">&copy; 1399 </p>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/profile_page.html
{% extends "accounts/base_account.html" %}
{% load static %}
{% block title %}نمایه کاربری{% endblock %}
{% block slider %}{% endblock %}
{% block main_content %}
<div class="container container-fluid">
    {% if error %}
        <div class="alert alert-danger"><h4 class="text-center">{{ error }}</h4></div>
    {% endif %}
{#{{ profile_filed }}#}
    <div class="row mb-2">
        <!-- part right-->
        <div class=" col-md-4">
            <!-- Sidebar -->
            <div class="col-md-10" style="overflow: hidden">
            <div class="bg-light border-right my-right-side" id="sidebar-wrapper">
              <div class="sidebar-heading">امکانات و فعالیت ها</div>
              <div class="list-group list-group-flush">
                  {% if user.is_staff %}
                <a href="{% url 'accounts:admin_panel' %}" class="list-group-item list-group-item-action bg-light">
                    <i class="fa fa-user-plus" aria-hidden="true"></i>پنل مدیریت</a>
                  {% endif %}
                <a href="{% url 'accounts:my_event' %}" class="list-group-item list-group-item-action bg-light">
                    <i class="fa fa-certificate my-icon" aria-hidden="true"></i>رویداد های من</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">
                    <i class="fa fa-history my-icon" aria-hidden="true"></i>تاریخچه رویداد ها</a>
                <a href="{% url 'accounts:add_new' %}" class="list-group-item list-group-item-action bg-light">
                    <i class="fa fa-plus my-icon" aria-hidden="true"></i>ایجاد یک رویداد</a>
                <a href="{% url 'accounts:admin_panel' %}" class="list-group-item list-group-item-action bg-light">
                    <i class="fa fa-bell my-icon" aria-hidden="true"></i>اعلان ها</a>
                <a href="{% url 'accounts:change_password' %}" class="list-group-item list-group-item-action bg-light">
                    <i class="fa fa-key my-icon" aria-hidden="true"></i>تغیر رمز عبور</a>
              </div>
            </div>
            </div>
            <!-- /#sidebar-wrapper -->
        </div>
        <!-- end part right-->
        <!-- part left-->
        <div class="col-md-8 themed-grid-col">
            <h6>مشخصات فردی</h6>
            <p>دراین قسمت می توانید مشخصات فردی خود‌را مشاهده و ویرایش کنید</p>
            <hr style="border-radius: 50%">
                <form action="#" class="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col col-md-8">
                            <div class="row mb-2">
                                <div class="col-md-6">
                                    <label for="id_first_name">نام:</label>
                                        <input type="text" id="id_first_name" name="first_name"
                                               class="form-control" value="{{ user.first_name }}">
                                </div>
                            <div class="col-md-6">
                                <label for="id_last_name">نام خانوادگی:</label>
                                    <input type="text" id="id_last_name" name="last_name"
                                           class="form-control" value="{{ user.last_name }}">
                            </div>
                        </div>
                        <div class="mb-3">
                             <label for="id_address">آدرس:</label>
                                <input type="text" id="id_address" name="address" class="form-control" value="{{ user.profile.address }}">
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label for="id_birth_date">تاریخ تولد:</label>
                                    <input type="text" id="id_birth_date" name="birth_date" class="form-control"
                                        value="{{ user.profile.birth_date|date:"yy-m-d" }}"
                                           onfocus="this.type='date'" onblur="(this.type='text')">
                            </div>
                            <div class="col-md-6">
                                <label for="id_user_type">نوع کاربری:</label>
                                <select id="id_user_type" name="user_type" class="form-control">
                                    <option value="" selected>مشخص نشده</option>
                                    <option value="1" {% if profile.user_type == 1 %}selected{% endif %}>حقیقی</option>
                                    <option value="2" {% if profile.user_type == 2 %}selected{% endif %}>حقوقی</option>
                                </select>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="id_organ_name">نام رسمی یا نام سازمان:</label>
                                <input type="text" id="id_organ_name" name="organ_name" class="form-control"
                                value="{{ user.profile.organ_name }}">
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label for="id_email">ایمیل:</label>
                                    <input type="email" id="id_email" name="email" class="form-control"
                                    value="{{ user.email }}">
                            </div>
                            <div class="col-md-6">
                                <label for="id_mobile">موبایل:</label>
                                    <input type="tel" id="id_mobile" name="mobile" class="form-control"
                                    value="{{ user.profile.mobile }}">
                            </div>
                        </div>
                        </div>
                        <!--left side profile image-->
                    <div class="col col-md-4 ">
                        <div class="row mb-3">
                            <div class="col-md-12">
                                <div class="card" style="padding: 10px">
                                    <img class="card-img-top" src="{% if profile.profile_image %}
                                        {{ profile.profile_image.url }}
                                      {% else %}
                                      {% static 'accounts/images/profile.png' %}
                                      {% endif %}" alt="user_profile">
                                    <div class="card-body">
                                        <p class="card-title" style="text-align: center">تصویر نمایه کاربری</p>
                                        <div class="row mb-2">
                                            <div class="col text-center">
                                                <label for="id_profile_image" class=""><i class="fa fa-pencil-alt" aria-hidden="true"></i></label>
                                                    <input id="id_profile_image" style="border: solid 1px #70767c"
                                                           class="form-control text-hide profile_image_edit_button" type="file" name="profile_image" accept="image/*" >
                                            </div>
                                            <div class="col text-center">
                                                <label for="profile_image-clear_id" class=""><i class="fa fa-times" aria-hidden="true"></i></label>
                                                    <input id="profile_image-clear_id"
                                                           class="form-control profile_image_edit_button" type="checkbox" name="profile_image-clear" accept="image/*" >
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 text-center">
                        <hr>
                        <div class="col-md-4" style="float: none; margin:30px auto auto auto;">
                            <button type="submit" class="btn btn-success">ثبت تغییرات</button>
                        </div>
                    </div>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}