accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
 path('login/', views.login_operation, name='login'),
 path('logout/', views.logout_operation, name='logout'),
 path('profile/', views.profile_view, name='profile'),
 path('profile/myevent/', views.my_events, name='my_event'),
 path('profile/addnew/', views.add_new_event, name='add_new'),
 path('profile/register/', views.register_user, name='register_user'),
 path('profile/change_password/', views.change_password, name='change_password'),
 path('profile/event_submitted/<int:event_id>', views.event_submitted, name='event_submitted'),
 path('profile/edit_event/<int:event_id>', views.edit_own_event, name='edit_own_event'),
 path('profile/admin_panel/', views.admin_panel, name='admin_panel'),
 path('profile/verify_event/<int:event_id>', views.verify_event, name='verify_event')
]

eventing/urls.py
from django.urls import path
from eventing import views

app_name = 'eventing'

urlpatterns = [
 path('home/', views.home_loader, name='home_loader'),
 path('event/list/', views.event_list, name='event_list'),
 path('event/details/<int:event_id>', views.event_details, name='event_details'),
]

social_event/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from eventing import views

urlpatterns = [
    path('', views.home_loader, name='home_loader'),
    path('admin/', admin.site.urls),
    path('eventing/', include('eventing.urls')),
    path('accounts/', include('accounts.urls'))
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventing/models.py
from django.db import models


class Event(models.Model):
    """
    Represents an event
    """
    class Meta:
        verbose_name = "رویداد"
        verbose_name_plural = "رویداد"

    title = models.CharField('عنوان', max_length=150, unique=True, blank=False)

    subject_choices = (
        ('computer science', 'علوم رایانه'),
        ('data science', 'علم داده'),
        ('big data', 'کلان داده'),
        ('artificial intelligence', 'هوش مصنوعی'),
        ('security', 'امنیت'),
        ('software engineering', 'مهندسی نرافزار'),
        ('develop', 'توسعه‌ی نرم افزار'),
        ('cryptography', 'رمزنگاری'),
        ('crypto currency', 'رمز ارز'),
        ('IOT', 'اینترنت اشیا'),
        ('startup', 'استارتاپ'),
    )
    subject = models.CharField('موضوع', choices=subject_choices, max_length=30, blank=False)
    tags = models.CharField('برچسب ها', max_length=70, null=True, blank=True)
    organizer = models.ForeignKey\
        ('accounts.Profile', on_delete=models.PROTECT, verbose_name='برگزار کننده')
    start_date = models.DateTimeField('زمان شروع', blank=False)
    end_date = models.DateTimeField('زمان پایان', blank=False)
    details = models.TextField('درمورد رویداد', max_length=2000, blank=False)
    poster = models.ImageField('پوستر', upload_to='event_posters/', blank=False)
    trailer = models.FileField('پیش نمایش', upload_to='event_trailers', null=True, blank=True)
    '#Represent situation of each event'
    EVENT_NOT_STARTED = 1
    EVENT_DONE = 2
    EVENT_STARTED = 3
    EVENT_CANCELED = 4
    NOT_VERIFY = 5
    situation_choices = (
        (EVENT_NOT_STARTED, 'رویداد آغاز نشده'),
        (EVENT_STARTED, 'رویداد آغاز شده'),
        (EVENT_DONE, 'رویداد پایان یافت'),
        (EVENT_CANCELED, 'رویداد لغو شده'),
        (NOT_VERIFY, 'در انتظار تایید')
    )
    situation = models.IntegerField\
        ('وضعیت رویداد', blank=True, choices=situation_choices, default=NOT_VERIFY)
    verify = models.BooleanField('تایید', null=False, blank=True, default=False)
    cancel = models.BooleanField('لغو', null=False, blank=True, default=False)
    end = models.BooleanField('پایان', null=False, blank=True, default=False)
    made_time = models.DateTimeField('زمان ایجاد', auto_now_add=True)

    def __str__(self):
        """
        override Event models *string representation* method
        """
        title = self.title
        if self.organizer.organ_name is not None:
            organizer = self.organizer.organ_name
        else:
            organizer = self.organizer.user.get_full_name()

        return 'عنوان:{}--زمان:{}--برگزار کننده:{}'.format(title, self.start_date, organizer)

    def cancel_event(self):
        """
        user/organizer canceled event
        """
        self.cancel = True
        self.situation = Event.EVENT_CANCELED

eventing/forms.py
from django import forms
from eventing.models import Event


class EventSearchForm(forms.Form):
    event_title = forms.CharField(label='عنوان رویداد', max_length=200, required=False)
    event_NOT_START = forms.BooleanField(label='فقط رویدادهای شروع نشده', required=False)
    subject_choices = Event.subject_choices
    event_subject = forms.ChoiceField(label='موضوع رویداد', choices=subject_choices, required=False)

eventing/views.py
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Event
from accounts.models import Submit
from .forms import EventSearchForm


def home_loader(request):
    """
    Load landing page
    """
    return render(request, 'eventing/base_page.html')


def event_list(request):
    """
    method for query from db to return all or searched events object and sent to client
    """
    events = Event.objects.filter(Q(cancel=False) and Q(verify=True))
    search_form = EventSearchForm(request.GET)
    if search_form.is_valid():
        if search_form.cleaned_data['event_title']:
            events = events.filter(title__contains=search_form.cleaned_data['event_title'])
        if search_form.cleaned_data['event_subject']:
            events = events.filter(subject=search_form.cleaned_data['event_subject'])
        if search_form.cleaned_data['event_NOT_START']:
            events = events.filter(situation=Event.EVENT_NOT_STARTED)
    events = events.order_by('-start_date')
    context = {
        'events': events,
        'search_form': search_form
    }
    return render(request, 'eventing/event_list.html', context)


def event_details(request, event_id):
    """
    method for query from db to return event details
    """
    event = Event.objects.get(pk=event_id)
    context = {
        'event': event
    }
    if request.user.is_authenticated:
        user = request.user.profile
        '#submit event'
        if request.method == 'POST':
            try:
                assert event.situation != event.EVENT_STARTED, 'رویداد درحال برگزاری میباشد'
                assert event.situation != event.EVENT_CANCELED, 'رویداد لغو شده است'
                assert event.situation != event.EVENT_DONE, 'رویداد به پایان رسیده است'
                assert event.situation != event.NOT_VERIFY, 'این رویداد تایید نشده است'
                assert check_submitted(user, event), 'شما قبلا ثبت نام کرده اید'
                Submit.objects.create(submitted_user=user, submitted_event=event)
                return HttpResponseRedirect(reverse('accounts:my_event'))
            except Exception as e:
                context['error'] = str(e)

    return render(request, 'eventing/event_details.html', context)


def check_submitted(user, event):
    """
    check user are submitted specific event
    """
    if Submit.objects.filter(submitted_user=user, submitted_event=event, cancel=False).exists():
        return False
    else:
        return True

eventing/templates/eventing/base_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'eventing/images/logo.png' %}" type="image/gif" sizes="16x16">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css"
          integrity="sha384-vus3nQHTD+5mpDiZ4rkEPlnkcyTP+49BhJ4wJeJunw06ZAp+wzzeBPUXr42fi8If"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "eventing/css/font-awesome.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "eventing/css/main.css" %}">
    {% block extra_css %}{% endblock %}
</head>

<body dir="rtl">
<!--navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <a class="navbar-brand" href="{% url 'eventing:home_loader' %}">
      <img src="{% static 'eventing/images/logo.png' %}" alt="logo" style="height: 45px"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'eventing:event_list' %}">رویدادها
            <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">درباره‌ما</a>
      </li>

    <!--user buttons-->
      {% block user_button %}
          {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                   role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-user" style="margin-left: 5px"></i>{{ user.get_full_name }}
                </a>
                <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
                    {% if user.is_staff %}
                    <a class="dropdown-item" href="{% url 'accounts:admin_panel' %}">
                        <i class="fa fa-user-plus" aria-hidden="true"></i>
                        پنل مدیریت
                    </a>
                    {% endif %}
                  <a class="dropdown-item" href="{%url "accounts:profile"%}">
                      <i class="far fa-address-card"></i>
                      نمایه‌کاربری
                  </a>
                  <a class="dropdown-item" href="{% url 'accounts:my_event' %}">
                      <i class="fas fa-ticket-alt"></i>
                      رویدادهای من
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{%url "accounts:logout" %}">
                      <i class="fas fa-sign-out-alt"></i>
                      خروج
                  </a>
                </div>
              </li>
              {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        <i class="fas fa-sign-in-alt"></i>
                        واردشوید
                        <span class="sr-only">(current)</span></a>
                </li>
          {% endif %}
      {% endblock %}

      <!--<li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>-->
    </ul>
    <form method="get" action="{% url 'eventing:event_list' %}" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search"
             placeholder="رویدادی را بگرد..." aria-label="Search">
      <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
    </form>
  </div>
</nav>
<!--end navbar-->
<!--slider-->
{% block slider %}
<div id="demo" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>

  <!-- The slideshow -->
  <div class="carousel-inner my-slider">
    <div class="carousel-item active">
      <img src="{% static 'eventing/images/slide1.jpg' %}" style="width: 100%;"
           alt="machine learning">
    </div>
    <div class="carousel-item">
      <img src="{% static 'eventing/images/slide2.jpeg' %}" style="width: 100%;"
           alt="deep learning">
    </div>
      <div class="carousel-item">
      <img src="{% static 'eventing/images/slide3.jpg' %}" style="width: 100%;"
           alt="deep learning">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>

</div>
{% endblock %}
<!--end slider-->

<div class="container-fluid">
    <div id="my-content">
        <h2 style="text-align: center;color: #bd2130" class="alert alert-warning">به پروژه من خوش آمدید :)))</h2>

<!-----main block----->
{% block main_content %}

    <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
      <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 py-3">
          <h2 class="display-5">رویداد</h2>
          <p class="lead">در اجتماع مجازی فعال باشید</p>
        </div>
        <div class="bg-light shadow-sm mx-auto"
             style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
      </div>
      <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
        <div class="my-3 p-3">
          <h2 class="display-5">وبینار</h2>
          <p class="lead">با دیگران گفتگو کنید</p>
        </div>
        <div class="bg-dark shadow-sm mx-auto"
             style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
      </div>
    </div>

    <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
      <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
        <div class="my-3 p-3">
          <h2 class="display-5">آموزش</h2>
          <p class="lead">از دانسته های دیگران بهره ببرید</p>
        </div>
        <div class="bg-dark shadow-sm mx-auto"
             style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
      </div>
      <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 py-3">
          <h2 class="display-5">بسازید</h2>
          <p class="lead">دانسته های خود را با دیگران به اشتراک بگزاید</p>
        </div>
        <div class="bg-light shadow-sm mx-auto"
             style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
      </div>
    </div>

{% endblock %}
<!----end main block---->
    </div>
    <!--footer-->
    <footer class="row align-content-center" id="my-footer">
        <div class="col text-center">
            <h6 style="color: yellow;margin: 10px;text-align: center">ما را در شبکه های اجتماعی دنبال کنید ;)</h6>
            <span>
                <a class="social-media-icon" href="https://facebook.com/">
                    <i class="fab fa-facebook"></i>
                </a>
                <a class="social-media-icon" href="https://instagram.com/">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="social-media-icon" href="https://telegram.org/">
                    <i class="fab fa-telegram-plane"></i>
                </a>
            </span>
            <p style="color: #ffffff;text-align: right;margin-bottom: 2px!important;font-size: 12px">پروژه تحلیل طراحی دانشگاه شهید چمران 1399-1398 &copy;</p>
        </div>
    </footer>

</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"
        integrity="sha384-a9xOd0rz8w0J8zqj1qJic7GPFfyMfoiuDjC9rqXlVOcGO/dmRqzMn34gZYDTel8k"
        crossorigin="anonymous"></script>
<script src="{% static "eventing/js/font-awesome.js" %}"></script>
<script src="{% static "eventing/js/main.js" %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

eventing/templates/eventing/event_details.html
{% extends "eventing/base_page.html" %}
{% load static %}
{% block title %}{{ event.title }}{% endblock %}
{% block slider %}{% endblock %}

{% block main_content %}
<div class="container container-fluid">
    <div class="row mb-2 main-details">
        <div class="col-md-8">
            <div class="event-poster-details">
                <img src="{{ event.poster.url }}" style="width: 100%;height: 100%">
            </div>
            <div class="detail-content">
                <h6 class="alert-success"
                style="padding: 6px; border-radius: 10px">درمورد رویداد : {{ event.title }}</h6>
                <hr style="border-radius: 50%">
                <p style="text-align: unset">
                {{ event.details }}
                </p>
                <hr>
            </div>
        </div>
        <div class="col-md-4">
            <div style="padding: 10px 0 20px 0">
                <h5 style="color: #007bff"><strong>{{ event.title }}</strong></h5>
                <dl class="event_detail">
                    <dt>موضوع:</dt>
                    <dd>{{ event.get_subject_display }}</dd>
                    <dt>برگزار کننده:</dt>
                    <dd>{{ event.organizer }}</dd>
                    <dt>شروع:</dt>
                    <dd>{{ event.start_date|date:"l n/j ساعت H:i" }}</dd>
                    <dt>پایان:</dt>
                    <dd>{{ event.end_date|date:"l n/j ساعت H:i" }}</dd>
                    <dt>وضعیت رویداد:</dt>
                    <dd>{{ event.get_situation_display }}</dd>
                </dl>
                <div class="text-center">
                    <form action="#" method="post">
                        {% csrf_token %}
                        <button name="submit_action" type="submit" class="btn btn-success">ثبت نام</button>
                    </form>
                <div class="text-center" style="margin-top: 20px">
                    {% if error %}
                        <span class="alert alert-danger text-center" style="padding: 10px">
                            {{ error }}
                        </span>
                    {% endif %}
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

eventing/templates/eventing/event_list.html
{% extends "eventing/base_page.html" %}
{% load static %}

{% block title %}
    ایونت ها
{% endblock %}

<!--main content block-->
{% block main_content %}
<div class="container container-fluid">
    <div class="row mb-1">
        <div class="col-md-12" style="float: none;margin: auto;background-color: #f5f5f5 ;">
            <form action="#" method="get">
                <div class="row mb-4" style="padding: 20px">
                    <div class="col-md-3">
                        <label for="{{ search_form.event_title.id_for_label }}">جستجو در نام:</label>
                            <input type="text" id="{{ search_form.event_title.id_for_label }}"
                                   class="form-control" name="{{ search_form.event_title.html_name }}">
                    </div>
                    <div class="col-md-3">
                        <label for="{{ search_form.event_subject.id_for_label }}">جستجو در موضوع:</label>
                        <select id="{{ search_form.event_subject.id_for_label }}" class="form-control"
                                name="{{ search_form.event_subject.html_name }}">
                        <option value="" selected>---</option>
                        {% for key,value in search_form.subject_choices %}
                            <option value="{{ key }}">{{ value }}</option>
                        {% endfor %}
                        </select>
                    </div>
                <div class="col-md-3">
                    <label for="{{ search_form.event_NOT_START.id_for_label }}"> فقط ایونت های آغاز نشده:</label>
                    <input type="checkbox" id="{{ search_form.event_NOT_START.id_for_label }}"
                           name="{{ search_form.event_NOT_START.html_name }}" class="form-control">
                </div>
                <div class="col-md-3">
                    <label></label>
                    <button type="submit" class="btn btn-success form-control">جستجو</button>
                </div>
                </div>
            </form>
        </div>
    </div>
</div>
    <div class="row">

        <div class="col py-3">
            {% if events %}
                <div class="row px-2">
                    <div class="col">
                        <div class="alert alert-info mt-2 mb-0 py-1 px-3"
                             style="border-radius: 30px; background-color: #d3d9df">
                            {{ events.count }}
                            رویداد یافت شد :)
                        </div>
                    </div>
                </div>
                <div class="row px-2">
                    {% for event in events %}
                        <div class="col-md-3 col-lg-3 col-8 col-sm-6 col-xl-3 px-3 py-2 event-section">
                            <div class="col-md-12 " style="margin-top: 50px;">
                                <div class="shadow p-3 mb-5 bg-white rounded boxed-event">
                                    <a href="{% url "eventing:event_details" event_id=event.id %}">
                                        {% if event.poster %}
                                            <img src="{{ event.poster.url }}" class="col-md-12 event-poster" alt="Poster">
                                            {% else %}
                                            <img src="{% static 'eventing/images/slide3.jpg' %}"
                                                 class="col-md-12 event-poster" alt="Poster">
                                        {% endif %}
                                    </a>
                                    <div class="col-md-12 event-content">
                                        <a href="{% url "eventing:event_details" event_id=event.id %}"
                                           style="text-decoration: none;">
                                            <p style="height: 35px"><b>{{ event.title }}</b></p>
                                        </a>
                                        <dl class="event_detail">
                                            <dt>شروع:</dt>
                                            <dd>{{ event.start_date|date:"l n/j ساعت H:i" }}</dd>
                                            <dt>پایان:</dt>
                                            <dd>{{ event.end_date|date:"l n/j ساعت H:i" }}</dd>
                                            <dt>برگزار کننده:</dt>
                                            <dd>{{ event.organizer.organ_name }}</dd>
                                        </dl>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="row px-2">
                    <div class="col">
                        <div class="alert alert-info mt-2 mb-0 py-1 px-3"
                             style="border-radius: 30px; background-color: #d3d9df">
                            هیچ رویدادی یافت نشد :(
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}